# privilegedPSP gives the privilegedPSP role
# to the group privileged.
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
    name: privilegedPSP
subjects:
- kind: Group
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  name: privileged
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: privilegedPSP
---
# restrictedPSP grants the restrictedPSP role to
# the groups restricted and privileged.
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
    name: restrictedPSP
subjects:
- kind: Group
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  name: restricted
- kind: Group
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  name: privileged
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: restrictedPSP
---
# cluster-writer grants cluster-writer role to system:authenticated.
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
    name: cluster-writer
subjects:
- kind: Group
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  name: system:authenticated
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: cluster-writer
