apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
    name: allPSP
subjects:
- kind: Group
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  name: privileged
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: privilegedPSP
 
