# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: no-ipc
  labels:
    name: no-ipc
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
