# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: priv
  labels:
    name: no-pid
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    securityContext:
        privileged: true
