# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile provides a simple default configuration using VirtualBox.
# For any other configuration, create a configuration in .vagrant-openshift.json
# using the vagrant-openshift plugin (https://github.com/openshift/vagrant-openshift)
# as an alternative to editing this file.
# Specific providers may use further configuration from provider-specific files -
# consult the provider definitions below for specifics.

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Require a recent version of vagrant otherwise some have reported errors setting host names on boxes
Vagrant.require_version ">= 1.7.1"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "devbox", primary: true do |config|
      #if vagrant_openshift_config['private_network_ip']
      #  config.vm.network "private_network", ip: vagrant_openshift_config['private_network_ip']
      #else
      #  config.vm.network "forwarded_port", guest: 80, host: 1080
      #  config.vm.network "forwarded_port", guest: 443, host: 1443
      #  config.vm.network "forwarded_port", guest: 8080, host: 8080
      #  config.vm.network "forwarded_port", guest: 8443, host: 8443
      #end
      config.vm.synced_folder ".", "/vagrant", disabled: true
      config.vm.synced_folder ENV['GOPATH'], "/data"
  end # vm definition(s)

  config.vm.provider "virtualbox" do |v, override|
      override.vm.box     = "f24-d1.12"
    override.vm.box_url = "~/codebase/vagrant-boxes/f24-d1.12.box"
    override.ssh.insert_key = true

    v.memory            = 8192
    v.cpus              = 4
    v.customize ["modifyvm", :id, "--cpus", "4"]
  end 
end
