# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile provides a simple default configuration using VirtualBox.
# For any other configuration, create a configuration in .vagrant-openshift.json
# using the vagrant-openshift plugin (https://github.com/openshift/vagrant-openshift)
# as an alternative to editing this file.
# Specific providers may use further configuration from provider-specific files -
# consult the provider definitions below for specifics.

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Require a recent version of vagrant otherwise some have reported errors setting host names on boxes
Vagrant.require_version ">= 1.7.1"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "devbox", primary: true do |config|
      # TODO: what is in this provisioner and do I need it?
      # config.vm.provision "setup", type: "shell", path: "contrib/vagrant/provision-minimal.sh"


      #if vagrant_openshift_config['private_network_ip']
      #  config.vm.network "private_network", ip: vagrant_openshift_config['private_network_ip']
      #else
      #  config.vm.network "forwarded_port", guest: 80, host: 1080
      #  config.vm.network "forwarded_port", guest: 443, host: 1443
      #  config.vm.network "forwarded_port", guest: 8080, host: 8080
      #  config.vm.network "forwarded_port", guest: 8443, host: 8443
      #end
      sync_to = ENV["KUBE_ROOT"] || '.'
      config.vm.synced_folder sync_to, "/data", type: "nfs"
  end # vm definition(s)

  config.vm.network "private_network", ip: "192.168.50.10"

  config.vm.provider "virtualbox" do |v, override|
    override.vm.box     = "fedora_inst"
    override.vm.box_url = "https://mirror.openshift.com/pub/vagrant/boxes/openshift3/fedora_virtualbox_inst.box"
    override.ssh.insert_key = true

    v.memory            = 4096
    v.cpus              = 2
    v.customize ["modifyvm", :id, "--cpus", "2"]
  end 
end
