# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    name: pod
  annotations:
      seccomp.security.alpha.kubernetes.io/pod: "foo"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
