# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: hostipc
  labels:
    name: userns
spec:
  hostIPC: true
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
